name: repo_viewer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.0 #for authentication
  flutter_secure_storage: ^4.2.0 #to store the access token
  dartz: ^0.10.0-nullsafety.1 #for the Either type so that we can do proper failure handling
  dio: ^4.0.0 #a better http client
  # hooks_riverpod:
  #   git:
  #     url: https://github.com/rrousselGit/river_pod.git
  #     ref: 82bb2a93fe78c23d91680d0a4da65bb6b4e5b02c
  #     path: packages/hooks_riverpod
  hooks_riverpod: 1.0.0-dev.2
  freezed_annotation: ^0.14.1 #for code generator
  webview_flutter: ^2.0.4
  flash: ^1.5.1 #to show really beautiful snackBars, and to display 'you are not online', etc.
  auto_route: ^3.0.4 #declarative navigation (not imperative, like the past one), for deep links (to be able to type in a URL and the user will be able to go precisely to that address). It uses code generation. Helps us use Navigator 2.0. Uses code generation.
  material_design_icons_flutter: 5.0.5955-rc.1
  json_annotation: ^4.3.0
  sembast: ^3.1.1
  path_provider: ^2.0.6
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1 #for code generator
  freezed: ^0.14.1+3 #for code generator
  lint: ^1.5.3 #enforces proper coding practices. Provides information for best code practices, lint rules.
  auto_route_generator: ^3.0.1   #code generator for Navigator 2.0
  json_serializable: ^6.0.1 #generator package


# dependency_overrides:
#   flutter_riverpod: 
#     git:
#       url: https://github.com/rrousselGit/river_pod.git
#       ref: cdb78ae8d0c9324aa88e87061f401429880dd432
#       path: packages/flutter_riverpod
#   riverpod:
#     git:
#       url: https://github.com/rrousselGit/river_pod.git
#       ref: cb9ce91dea5a652a0a0f7f753ebba682a1b829f5
#       path: packages/riverpod

flutter:
  uses-material-design: true


